using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MVVM_GMI.Services
{
    public interface IUserProfile
    {
        /// <summary>
        /// Username returned by the database which matches the InstallationID and AuthKey
        /// </summary>
        String AuthorizedUsername { get; set; }

        /// <summary>
        /// Username initially set by the user while waiting for confirmation/membership
        /// </summary>
        String Username { get; set; } 

        /// <summary>
        /// Valid hashed-password that is the same with the one in the database
        /// </summary>
        String AuthKey { get; set; }

        /// <summary>
        /// ID generated for the current installation which is the only device that allows
        /// the username to be used.
        /// </summary>
        String InstallationID { get; set; }

        /// <summary>
        /// A Key generated by a user to invite another player
        /// </summary>
        String UserInviteCode { get; set; }

    }
}
