using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MVVM_GMI.Services
{
    public class UserProfileService
    {

        private static readonly Lazy<UserProfileService> lazyInstance = new Lazy<UserProfileService>(() => new UserProfileService());

        public static UserProfileService Instance => lazyInstance.Value;

        private UserProfileService()
        {
            // Private constructor to prevent instantiation outside the class
        }
        
        



        /// <summary>
        /// Username returned by the database which matches the InstallationID and AuthKey
        /// </summary>
        public String AuthorizedUsername { get; set; }

        /// <summary>
        /// Username initially set by the user while waiting for confirmation/membership
        /// </summary>
        public String Username { get; set; }

        /// <summary>
        /// Valid hashed-password that is the same with the one in the database
        /// </summary>
        public String AuthKey { get; set; }

        /// <summary>
        /// ID generated for the current installation which is the only device that allows
        /// the username to be used.
        /// </summary>
        public String InstallationID { get; set; }

        /// <summary>
        /// A Key generated by a user to invite another player
        /// </summary>
        public String UserInviteCode { get; set; }

    }
}
